name: Build and Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  npm-security-tests:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout of the Repo
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Run npm Security Tests
      run: npm run test-npm-audit
  
  integration-tests:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 21.x, 22.x]

    steps:
    - name: Checkout of the Repo
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test

  deploy-render:
    runs-on: ubuntu-latest
    needs: [integration-tests]
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true